service:
  type: NodePort
  nodePorts:
    external: "your_kafka_service_port" 
externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  controller:
    service:
      type: NodePort
      nodePorts: 
        - your_kafka_controller_1_port
        - your_kafka_controller_2_port
        - your_kafka_controller_3_port
listeners:
  external:
    protocol: PLAINTEXT
rbac:
  create: true